### ISSUE TITLE
Tensorflow & CUDA versions

### ISSUE THREAD

**Issue by Jeremy26** [understand-ai/anonymizer#4]
Hello,

I followed the exact README you have and got the cuda error ``` 
E   ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
``` when running ```pytest```.

Probably a compatibility between tensorflow-gpu version and CUDA version issue

**Comment by seb-uai** [comment]
Yes, sounds like it.
Can you let me know if CUDA 9.0.176-1 with CUDNN 7.0.3 work?

These commands install the CUDA version under ubuntu:
```
curl -O http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_8.0.61-1_amd64.deb
  dpkg -i ./cuda-repo-ubuntu1404_8.0.61-1_amd64.deb
  apt-get update
  apt-get install cuda=9.0.176-1 -y
  apt-get install linux-headers-$(uname -r) -y
```

You can download CUDNN 7.0.3 directly from nvidia.

**Comment by Ryan-Maughan** [comment]
I had the same issue running Ubuntu 18.04 through Hyper-V. The problem is the GPU appears incompatible with tensorflow-gpu. I fixed this with the following:

> In case you want to run the model on CPU, make sure that you install tensorflow instead of tensorflow-gpu listed in the requirements.txt.

**Comment by scaidermern** [comment]
Got the same problem on Debian. I solved it by installing nvidia-cuda-dev from testing (version 10.2.x). stable has 9.2.x which seems to be too old.

**Comment by federicochiesa** [comment]
I have the same error on Ubuntu 20.04, but apparently there's no way to install CUDA 9 on this OS, so how can I solve this?
